name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Setup Elixir cache
        uses: actions/cache@v4
        with:
          key: elixir-deps-${{ hashFiles('flake.lock') }}-${{ hashFiles('mix.lock') }}
          restore-keys: elixir-deps-${{ hashFiles('flake.lock') }}-
          path: |
            deps/
            _build/

      - name: Install deps
        run: nix develop --command mix deps.get

      - name: Run tests
        run: nix develop --command mix test
