name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Elixir cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-elixir-deps
          path: |
            deps/
            _build/

      - name: Install deps
        run: nix develop --command mix deps.get

      - name: Run tests
        run: nix develop --command mix test
